modLoader="javafml" #mandatory
loaderVersion="[43,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"
[[mods]] #mandatory
modId="oddorganisms" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Odd Organisms" #mandatory
credits="Peeko for Unusual Prehistory, and Wadoo, Orca, Hirbbert, Alpha Gec for animations" #optional
authors="Coda" #optional
description='''
This is an addon to the Unusual Prehistory mod by Peeko32213 that adds more prehistoric creatures!'''
[[dependencies.oddorganisms]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[43,)" #mandatory
    ordering="NONE"
    side="BOTH"
# Here's another dependency
[[dependencies.oddorganisms]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"
[[dependencies.oddorganisms]]
    modId="unusualprehistory"
    mandatory=true
    versionRange="[1.3.0,1.4.0)"
    ordering="BEFORE"
    side="BOTH"